language: erlang
elixir:
  - 1.2.4
otp_release:
  - 18.3

# It would be possible to use the container-based infrastructure if
# it ran trusty. However, it doesn't and wget is too old to use for
# HTTPS to buildroot.net.
sudo: required
dist: trusty

# Install dependencies
addons:
  apt:
    packages:
    - bc
    - libssl-dev

# Cache downloaded files between builds
cache:
    directories:
      - $HOME/.nerves/cache/buildroot

env:
  - ELIXIR_VERSION=1.2.4 NERVES_SYSTEM_CACHE=none NERVES_SYSTEM_COMPILER=local CI_SYSTEM_NAME=nerves_system_bbb

before_install:
    - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
    - unzip -d elixir Precompiled.zip

before_script:
    - export PATH=`pwd`/elixir/bin:$PATH

script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix archive.install https://github.com/nerves-project/archives/raw/master/nerves_bootstrap.ez --force
  - mix deps.get
  - mix compile

# Deploy the build products
before_deploy:
    - mix compress.nerves_system
    - deps/nerves_system_br/scripts/ci-deploy.sh
deploy:
  # Deploy tagged releases to GitHub
  - provider: releases
    api_key: $GITHUB_API_KEY
    file:
      - "artifacts/$CI_SYSTEM_NAME-$TRAVIS_TAG.tar.gz"
      - "artifacts/$CI_SYSTEM_NAME-$TRAVIS_TAG.fw"
    skip_cleanup: true
    on:
      repo: nerves-project/nerves_system_bbb
      tags: true
  # Copy all build products to S3
  - provider: s3
    access_key_id: $ARTIFACTS_KEY
    secret_access_key: $ARTIFACTS_SECRET
    bucket: $ARTIFACTS_BUCKET
    skip_cleanup: true
    local_dir: artifacts
    upload-dir: nerves_system_bbb
    storage_class: "REDUCED_REDUNDANCY"  # See https://github.com/travis-ci/dpl/issues/291
    on:
      repo: nerves-project/nerves_system_bbb
      all_branches: true

# Display build log on failure
after_failure:
    - tail -n 1000 build.log
